oomol/oocana-rust

.github/workflows/publish.yml
Cargo.lock
Cargo.toml
cli/Cargo.toml
npm/npm.mjs
npm/utils.mjs

- **fix: use tar.gz to avoid missing executable permission**
- **refactor: avoid download binary from release and delete oocana-cli package**
- **feat(action): support build local**
- **feat: support publish for everyone**
- **avoid artifact conflict**
- **fix working directory**
- **add log**
- **fix download directory**
- **add filter for trigger**

chore(action): fix release has no executable permission

---

.github/workflows/build-and-test.yml
README.md
README.zh-CN.md
cspell.json

- **docs: update readme**
- **chore: update cspell**
- **chore(action): add path for push**

chore: update readme and improve action

---

runtime/src/block_job/task_job.rs

1. report every stdout as log
2. add stderr as output
3. use shell command exit code to consider success or fail

feat: improve shell executor

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
one_shot/src/one_shot.rs
runtime/src/block_job/task_job.rs
runtime/src/lib.rs

- **feat: avoid print error message by default**
- **refactor: rename exit message**
- **chore: remove print log**

feat: improve exit message

---

Cargo.lock
mainframe/src/scheduler.rs
manifest_meta/Cargo.toml
manifest_meta/src/block_resolver.rs
manifest_meta/src/flow.rs
manifest_meta/src/lib.rs
manifest_meta/src/node.rs
manifest_meta/src/scope.rs
manifest_meta/src/task.rs
manifest_reader/src/manifest/mod.rs
runtime/src/block_job/block.rs
runtime/src/block_job/listener.rs
runtime/src/block_job/service_job.rs
runtime/src/block_job/task_job.rs
runtime/src/flow_job/flow.rs
runtime/src/lib.rs

- use running scope to reflect block's running environment and executor identifier (for now still call package)

feat: using running scope to support spawn and inject to spawn node feature

---

Cargo.lock
Cargo.toml
cli/Cargo.toml
mainframe/src/scheduler.rs

- **fix: exclude package should be global**
- **chore: v0.24.2**

fix: exclude package fallback should be global

---

cli/src/fun.rs
cli/src/layer.rs
cli/src/lib.rs
layer/src/layer.rs
layer/src/package_layer.rs
layer/src/package_store.rs
layer/src/runtime_layer.rs
layer/tests/package.rs
layer/tests/runtime.rs
mainframe/src/scheduler.rs
one_shot/src/one_shot.rs

1. remove old env files parameter
2. add env file variable and env file load logic
3. pass env file values to layer creation
env file format:
```shell
k=v
```

feat: add env file parameter for run and layer create subcommand

---

layer/src/layer_settings.rs
layer/src/package_store.rs
mainframe/src/scheduler.rs
manifest_meta/src/flow.rs
manifest_meta/src/scope.rs
manifest_meta/src/task.rs
manifest_reader/src/manifest/node/node.rs
manifest_reader/src/path_finder/mod.rs
manifest_reader/src/path_finder/search_paths.rs

- **fix: improve error message for missing package file**
- **chore(test): add test case**
- **fix: relative block also have package path which make package path not reliable**
- **docs: add more detail error message**
- **fix: filter empty layer**
this PR will fix following flow run in layer feature:
```yaml
nodes:
- node_id: block-1
task: ./a
```

fix: relative block should run in global scope

---

cli/src/lib.rs

- **refactor: rename extra_bind_paths to bind_paths**
- **feat: add verbose**

feat(cli): add verbose argument and rename extra_bind_paths to bind_paths

---

README.md
README.zh-CN.md
mainframe/src/scheduler.rs
manifest_meta/src/scope.rs

Since every executor has an identifier, the suffix is no longer needed. This pull request need executor update.

refactor: remove suffix

---

manifest_meta/src/flow.rs
manifest_meta/src/task.rs
manifest_reader/src/manifest/block/task.rs
manifest_reader/src/manifest/node/node.rs

- **feat: add additional_inputs**
- **feat: implement additional_inputs merge**

feat: addition inputs

---

Cargo.lock
cli/src/lib.rs
mainframe/Cargo.toml
mainframe/src/scheduler.rs
one_shot/src/one_shot.rs

1. enable wait client feature.
2. python debugpy need a unused port.

feat: improve debug feature

---

layer/src/package_store.rs

- **refactor: improve error handling in package_meta and load_package_store functions**
- **fix: truncate file before write**

fix: truncate file before save

---

README.md
README.zh-CN.md
docs/configuration.md

- **docs: add configuration docs**
- **docs: update readme**
- **docs: update**

docs: add configuration docs

---

mainframe/src/scheduler.rs

- **feat: pass pkg dir to layer**
- **feat: implement pkg dir outside layer**
- **feat: pass OOCANA PKG DIR to executor**
`OOCANA_PKG_DIR` is only added to python and nodejs executor runtime. And is not exist in layer creation.

feat: add pkg dir

---

manifest_meta/src/flow.rs
manifest_meta/src/node.rs
manifest_reader/src/manifest/node/task.rs
runtime/src/block_job/block.rs
runtime/src/block_job/task_job.rs
runtime/src/flow_job/flow.rs
runtime/src/lib.rs

- **refactor: use timeout instead of timeout seconds**

refactor: use timeout instead of timeout seconds

---

manifest_meta/src/connections.rs
manifest_meta/tests/flow_test/flow-2/subflow.oo.yaml
manifest_reader/src/manifest/node/input_from.rs

- **refactor: rename from_subflow to from_flow**
- **refactor: rename variable name**
- **feat: remove from slot field**

refactor: remove from_slot and rename from_subflow to from_flow

---

.github/workflows/build-and-test.yml
job/src/lib.rs
job/src/scope.rs
mainframe/src/scheduler.rs
manifest_meta/src/flow.rs
manifest_meta/src/scope.rs
runtime/src/block_job/block.rs
runtime/src/block_job/listener.rs
runtime/src/block_job/service_job.rs
runtime/src/block_job/task_job.rs
runtime/src/flow_job/flow.rs
runtime/src/lib.rs

refactor: refactor running scope to two level struct

---

.github/workflows/layer.yml
runtime/src/flow_job/flow.rs
runtime/src/lib.rs

- **fix: slot and flow scope need follow parent scope layer**
- **feat: current give up workspace layer**
- **chore: test layer for all changes**

fix: current workspace give up layer

---

cli/src/lib.rs
mainframe/src/scheduler.rs
one_shot/src/one_shot.rs
runtime/src/lib.rs

The directory of the block path should take precedence over the current directory.

fix: default package should be block path's directory

---

one_shot/src/one_shot.rs

- **refactor:  format**
- **fix: remove session id in tmp dir**
- **refactor: improve flow tmp logic**

refactor: improve flow tmp logic

---

manifest_meta/src/connections.rs
manifest_meta/src/flow.rs
manifest_meta/src/node/common.rs
manifest_meta/src/node/definition.rs
manifest_reader/src/manifest/node/value.rs
runtime/src/flow_job/node_input_values.rs

Before this pull request: The value node could only connect to task nodes.
After this pull request: The value node can now connect to all types of nodes.

feat: make value node support all other nodes

---

manifest_meta/src/node/definition.rs
runtime/src/flow_job/flow.rs

- **fix: slot node should return slot scope**
- **fix: flow scope should follow flow's scope not flow's parent**

fix: wrong scope transform

---

mainframe/src/reporter/block_reporter.rs
mainframe/src/reporter/flow_reporter.rs
mainframe/src/scheduler.rs
runtime/src/block_job/listener.rs
runtime/src/block_job/task_job.rs
runtime/src/block_status.rs
runtime/src/flow_job/flow.rs
runtime/src/lib.rs

- **refactor: rename name**
- **refactor: format**
- **refactor: extract to function**
- **refactor: simplify**
- **feat: add output map feature**
- **fix: check done should be on every done report**
- **refactor: extract flow finish work**
- **refactor: extract flow success work to new function**

feat: add output map support

---

mainframe/src/reporter/block_reporter.rs
mainframe/src/reporter/mod.rs
mainframe/src/scheduler.rs
runtime/src/block_job/block.rs
runtime/src/block_job/listener.rs
runtime/src/block_job/task_job.rs
runtime/src/block_status.rs
runtime/src/flow_job/flow.rs

- **feat: reporter and receive finish message add result field**
- **refactor: use owned type not borrowed type**
- **feat: reporter add result on done (rename to finished)**
- **feat(runtime): follow underlying api change**
- **feat: add result to done**
- **feat: follow underlying api**
- **feat: consider todo**
- **fix: remove wrong usage**
- **feat: send result**

feat: improve finish message, support finish with some result

---

layer/src/layer.rs
layer/src/ovmlayer.rs
layer/src/package_layer.rs
layer/tests/package.rs

- **feat: follow underlying api**
- **chore: use test branch**

feat: follow underlying export import api update

---

.github/actions/ovmlayer/action.yml
.github/workflows/build-and-test.yml
.github/workflows/layer.yml
.github/workflows/oocana-node.yml
.github/workflows/oocana-python.yml

chore: test node and python both

---

cli/src/fun.rs
mainframe/src/scheduler.rs
one_shot/src/one_shot.rs
runtime/src/block_job/listener.rs
runtime/src/flow_job/flow.rs

- **refactor: auto format**
- **refactor: improve log message**
- **refactor: reduce return parameters**
- **chore: add more logs**
- **chore: improve log**
- **refactor: change log level**

refactor: improve log

---

manifest_meta/src/flow.rs
manifest_meta/src/scope.rs
manifest_reader/src/manifest/node/task.rs
manifest_reader/src/path_finder/block.rs
manifest_reader/src/path_finder/mod.rs
manifest_reader/src/path_finder/search_paths.rs
manifest_reader/src/path_finder/service.rs
runtime/src/block_job/listener.rs

- **refactor: block value type return enum struct**
- **follow underlying change**
- **refactor: remove**
- **refactor: remove info**
- **flow underlying api change**
- **refactor: rename**
- **refactor: pass block value type as parameters**
- **feat: make slot flow only accept self block for now**

feat: refactor search type and make slotflow only accept self block

---

manifest_reader/src/path_finder/search_paths.rs

- **chore: add test case**
- **refactor: pass path not vec**
- **refactor: use &[T] instead of &vec[T]**

refactor: refactor some parameters

---

.github/workflows/layer.yml

if all require check use same name. GitHub auto merge will merge if one job finish.

chore(action): rename action to avoid duplicate require check only wait one job

---

runtime/src/flow_job/node_input_values.rs

fix: remember options need change node fulfill logic

---

manifest_meta/src/connections.rs
manifest_meta/src/flow.rs
manifest_reader/src/manifest/node/subflow.rs

- **refactor: add slotProvider suffix**
- **feat: convert slot provider input from to flow input output and slot node input output**
- **refactor: rename**
- **refactor: use .. syntax**

feat: support add slot input

---

manifest_meta/src/flow.rs
runtime/src/flow_job/flow.rs

- **fix: flow_inputs_tos added twice**
- **chore: improve log**

fix: the addition of the slot input should not replicate flows inputs to

---

.github/workflows/build-and-test.yml
.github/workflows/layer.yml
manifest_reader/src/manifest/node/subflow.rs

- **chore: remove inline slot test**
- **chore(action): require rust job success**

chore: improve github action check

---

examples/input/blk_i/block.oo.yaml
examples/input/flow.oo.yaml
runtime/src/flow_job/flow.rs
tests/test_query.rs
tests/test_run.rs

- **feat: log warning for missing inputs nodes**
- **feat: only output absence input**
- **test: check output message**
- **test: add some value**

feat: log warning for missing inputs nodes

---

mainframe/src/scheduler.rs
manifest_meta/src/flow.rs

- **chore: use debug for executor stderr message**
- **fix: wrong log condition**

chore: improve log

---

.github/workflows/oocana-node.yml

https://github.com/oomol/oocana-rust/pull/214 is break change. so this pull request will update y version.

chore: add branch comment

---

manifest_reader/src/manifest/block/task.rs

- **feat: compatible handle group**
- **test: add group test case**

feat: compatible with group

---

job/src/lib.rs
job/src/scope.rs
mainframe/src/scheduler.rs
manifest_meta/src/flow.rs
manifest_meta/src/lib.rs
manifest_meta/src/node/definition.rs
manifest_meta/src/node/subflow.rs
manifest_meta/src/scope.rs
manifest_reader/src/path_finder/search_paths.rs
runtime/src/block_job/block.rs
runtime/src/block_job/listener.rs
runtime/src/block_job/service_job.rs
runtime/src/block_job/task_job.rs
runtime/src/flow_job/flow.rs
runtime/src/lib.rs

pass pgk_name to scope, so that executor can know the layer's relative package name.

feat: add pkg_name to target and scope

---

Cargo.lock
one_shot/Cargo.toml
one_shot/src/one_shot.rs
runtime/src/lib.rs

- **feat: layer feature based on exclude parameter**
- **feat: consider block**

fix: block need consider whether it should be run in layer or not

---

runtime/src/flow_job/node_input_values.rs
utils/src/output.rs

- **fix: deserialized no serialize path var**
- **docs: add comment**

fix: cache deserializable check failed

---

runtime/src/flow_job/flow.rs
runtime/src/flow_job/node_input_values.rs
utils/src/output.rs

- **feat: calculate some is_json_serializable**
- **fix: merge value.maybe_serializable check to update logic some it won't missing use**
- **refactor: unify deserializable  maybe_serializable logic and add forward compatibility**

refactor: improve cache serialize logic

---

manifest_meta/src/block.rs
manifest_meta/src/lib.rs
manifest_meta/tests/flow_test/task.oo.yaml
one_shot/src/one_shot.rs

- **refactor: more Human-readable**
- **feat: exclude package use starts_with instead of full equal**
- **refactor: make package path search more compatible**
- **refactor: make search more compatible**
- **refactor: rename and reduce init**

refactor: some improve

---

manifest_meta/src/block_resolver.rs

refactor: detect block type base on file name if filename is specific name

---

cli/src/layer.rs

- **fix: still import package layer even if package file not exist**
- **refactor: rename**

feat: import layer even if no package file

---

cli/src/layer.rs
layer/src/package_layer.rs

1. still import package layer if package file not exist
2. move layers code to new dir in package layer

fix: move path to new package path

---

runtime/src/flow_job/flow.rs

print error message use `[node id: <node>]`

feat: format failed message

---

runtime/src/block_job/block.rs
runtime/src/block_job/mod.rs
runtime/src/block_job/service_job.rs
runtime/src/block_job/task_job.rs
runtime/src/flow_job/flow.rs
runtime/src/flow_job/mod.rs
runtime/src/lib.rs
runtime/src/run/mod.rs

- **refactor: remove unnecessary wrap**
- **refactor: rename the specific job execution to "execute," while retaining "run" for the general tasks.**

refactor: fn name

---

Cargo.lock
mainframe/src/scheduler.rs
one_shot/Cargo.toml
one_shot/src/one_shot.rs
runtime/Cargo.toml
runtime/src/flow_job/block_request.rs
runtime/src/flow_job/flow.rs
runtime/src/flow_job/mod.rs
runtime/src/lib.rs
runtime/src/run/mod.rs
vault/src/lib.rs

- **refactor: expose return type and use &str instead of String**
- **feat: support block request vault**

feat: support oauth token

---

Cargo.lock
mainframe/src/scheduler.rs
one_shot/Cargo.toml
one_shot/src/one_shot.rs
runtime/Cargo.toml
runtime/src/flow_job/block_request.rs
runtime/src/flow_job/flow.rs
runtime/src/flow_job/mod.rs
runtime/src/lib.rs
runtime/src/run/mod.rs
vault/src/lib.rs

This reverts commit f179a54cc19921c14782d3711a558857d3738e3d.

feat: revert support oauth token (#332)

---

Cargo.lock
Cargo.toml
examples/condition/end/Cargo.toml
examples/condition/end/block.oo.yaml
examples/condition/end/src/main.rs
examples/condition/flow.oo.yaml
examples/condition/start/Cargo.toml
examples/condition/start/block.oo.yaml
examples/condition/start/src/main.rs
manifest_meta/src/block.rs
manifest_meta/src/condition.rs
manifest_meta/src/flow.rs
manifest_meta/src/lib.rs
manifest_meta/src/node/definition.rs
manifest_meta/src/node/mod.rs
manifest_reader/src/manifest/block/condition.rs
manifest_reader/src/manifest/block/mod.rs
manifest_reader/src/manifest/mod.rs
manifest_reader/src/manifest/node/condition.rs
manifest_reader/src/manifest/node/definition.rs
manifest_reader/src/manifest/node/mod.rs
runtime/src/block_job/condition.rs
runtime/src/block_job/mod.rs
runtime/src/flow_job/flow.rs
runtime/src/lib.rs
runtime/src/run/mod.rs
tests/test_run.rs

- **feat: add condition block**
- **implement enum**
- **feat: implement operator**
- **docs: add docs**
- **feat: remove**
- **feat: add condition node**
- **feat: add condition**
- **feat: add default condition**
- **docs: add docs**
- **export**
- **feat: add match**
- **feat: add condition meta**
- **feat: run condition job**

feat: implement inline condition block
